local levelTemplates = require("levels.level_templates")
local level = {}
-- 1
level[1] = levelTemplates.get(1)
level[2] = levelTemplates.get(2)
level[3] = levelTemplates.get(3)
level[4] = levelTemplates.get(4)
level[5] = levelTemplates.get(5)
level[6] = levelTemplates.get(1)
level[7] = levelTemplates.get(1)
-- 2
level[8] = levelTemplates.get(1)
level[9] = levelTemplates.get(1)
level[10] = levelTemplates.get(1)
level[11] = levelTemplates.get(1)
level[12] = levelTemplates.get(1)
level[13] = levelTemplates.get(1)
level[14] = levelTemplates.get(1)
-- 3
level[15] = levelTemplates.get(1)
level[16] = levelTemplates.get(1)
level[17] = levelTemplates.get(1)
level[18] = levelTemplates.get(1)
level[19] = levelTemplates.get(1)
level[20] = levelTemplates.get(1)
level[21] = levelTemplates.get(1)
-- 4
level[22] = levelTemplates.get(1)
level[23] = levelTemplates.get(1)
level[24] = levelTemplates.get(1)
level[25] = levelTemplates.get(1)
level[26] = levelTemplates.get(1)
level[27] = levelTemplates.get(1)
level[28] = levelTemplates.get(1)
-- 5
level[29] = levelTemplates.get(1)
level[30] = levelTemplates.get(1)
level[31] = levelTemplates.get(1)
level[32] = levelTemplates.get(1)
level[33] = levelTemplates.get(1)
level[34] = levelTemplates.get(1)
level[35] = levelTemplates.get(1)
-- 6
level[36] = levelTemplates.get(1)
level[37] = levelTemplates.get(1)
level[38] = levelTemplates.get(1)
level[39] = levelTemplates.get(1)
level[40] = levelTemplates.get(1)
level[41] = levelTemplates.get(1)
level[42] = levelTemplates.get(1)
-- 7
level[43] = levelTemplates.get(1)
level[44] = levelTemplates.get(1)
level[45] = levelTemplates.get(1)
level[46] = levelTemplates.get(1)
level[47] = levelTemplates.get(1)
level[48] = levelTemplates.get(1)
level[49] = levelTemplates.get(1)
return level